### ISSUE TITLE
Playout

### ISSUE THREAD

**Issue by NiklasSabel** [ocpm/ocpa#10]
Hey all,

I'm using the library to work on my master thesis and was wondering if you have already implemented something like a playout algorithm to sample traces from a given object-centric petri net?

Thanks a lot!

Best,
Niklas

**Comment by niklasadams** [comment]
Hi Niklas,
there is some playout calculated for precision and fitness. Maybe you can adapt that? However, this is not that trivial: The state space needs to be explored to find the "right way" to root all required object tokens to the correct next activity/transition. Depending on the number of objects, this might take an extensive amount of time. 
Best
Niklas
