### ISSUE TITLE
Parameters - query

### ISSUE THREAD

**Issue by nsankar** [ocpm/ocpa#4]
@niklasadams I have the following queries about the parameters used

(1) object_types = ["application", "offer"]  cited in the example code.

The question is the above list mentioned is related to which column in the example CSV file - BPI2017) **?**

(2) To which columns in BPI207 can we relate the val_names [ ] parameters to?

(3) Can you please share another dataset (like BOI2017) to study?

Many thanks for considering my request.

**Comment by niklasadams** [comment]
Hi!

In general, the different parameters only map different concepts to the CSV's columns. You are free to map however you choose. Some rules are important to consider (see the provided CSV file for reference).

1. event_timestamp and event_activity columns need to be present and also named in exactly this way.
2. Every column with a prefix of event_ will be considered an event attribute.
3. Every column can be an object type. But it should be explicitly chosen by the parameter in the import. The columns that are not chosen will be converted into event attributes.
4. The cells in the object type columns should be formatted in a way that Python can interpret the cell content as a list of objects. See the provided CSV file for reference. 
5. You can access the CSV and its values (very efficiently) through OCEL.get_value.
We will provide some more extensive tutorials on importing CSVs sometime in the future!
Real-life datasets are tricky to obtain but we will try to provide more like BPI2017! But there are also the ones shared on ocel-standard.org which are interesting to study.
Best
Niklas

**Comment by nsankar** [comment]
@niklasadams  Thank you.
